name: Build AAB

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Login to Expo
        env:
          EXPO_EMAIL: ${{ secrets.EXPO_EMAIL }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
        run: |
          echo $EXPO_PASSWORD | expo login -u $EXPO_EMAIL -p $EXPO_PASSWORD --non-interactive

      # - name: Configure EAS
      #   run: eas build:configure

      - name: Build AAB
        run: eas build --platform android --profile production --non-interactive

      - name: Upload AAB to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aab
          path: |
            build/*.aab
            **/*.aab
